### ISSUE TITLE
Use ABORT instead of STOP!

### ISSUE THREAD

**Issue by Philipp137** [adaptive-cfd/WABBIT#20]
### ERROR Messaging in WABBIT

Please avoid using the `stop` command! Using `stop` instead of `MPI_abort`can leave some processes on the computation nodes, without aborting them.
If you see it in any of the modules replace it by one of the following routines (`use module_globals`):

`call abort( <some ID>, <your error message>) ` 
`call abort( <your error message>) ` 
`call abort( <some ID>) `

Example: `call abort(10092018, "Error: this is my error message")`

This routine is a wrapper for `MPI_ABORT`, which is awesome because your module does not need to know the MPI Communicator or any other extra variable needed for error messaging.

**Comment by Arcadia197** [comment]
No stop routine left in code
