### ISSUE TITLE
homogenize sponge parameters for NS and ACM?

### ISSUE THREAD

**Issue by tommy-engels** [adaptive-cfd/WABBIT#21]
The ACM module reads the section 

```
[Sponge]
; sponge term, used in ACM module to mimick outflow conditions for pressure waves
use_sponge=0;
L_sponge=0.1;
C_sponge=1.0e-2;
```

from the ini file, while NS reads

```
[Physics]
...
; sponge (yes=1, no=0) NOTE: this setting here applies only to the compressible Navier-Stokes
; equation, not to other physics modules. For ACM, use the "sponge" section.
sponge_layer=1;
; sponge parameter
C_sp=0.001;
```

if not too much trouble, I suggest to remove the NS-specific part, as it can easily be merged with the `[Sponge]` section.
This is optional and not urgent, though.

**Comment by Philipp137** [comment]
Is done allready! I just forgot to remove it from the PARAMS_TEMPLATE.ini.
