### ISSUE TITLE
flusi_to_wabbit not working as before with different Bs implemented (but not used in my case)

### ISSUE THREAD

**Issue by MaximilianSchuster** [adaptive-cfd/WABBIT#28]
I cannot find a way to opt out if I have the same Bs for both directions in 2D.

**Comment by tommy-engels** [comment]
please post more details on your problem: call, input parameter, type of failure, screen output

**Comment by MaximilianSchuster** [comment]
used flusi-to-wabbit with a 2D file created by command

`insect.write_flusi_HDF5('p_00.h5', 0, [0, 0.4,0.2], Q1, viscosity=0.0, origin=np.array([0.0,0.0,0.0]))`

(this worked with the old version for a 2D domain with jmin=jmax=3, Bs=33)
then tried to convert flusi to wabbit by using 
`wabbit-post --flusi-to-wabbit p_00.h5 p_000000000000.h5 33`

got error message:

At line 69 of file LIB/POSTPROCESSING/flusi_to_wabbit.f90
Fortran runtime error: End of file

then realised we have a new inputs and executed the command
`wabbit-post --flusi-to-wabbit p_00.h5 p_000000000000.h5 33 33 1 `
(33 in x, 33 in y, but no z direction, if that makes sense)

got the error:

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.


Backtrace for this error:
#0  0x7FD33A3F9D47
#1  0x7FD33A3FA34E
#2  0x7FD33877311F
#3  0x57061F in flusi_to_wabbit_ at flusi_to_wabbit.f90:83
#4  0x410065 in main_post at main_post.f90:98
Floating point exception

I dont know what the correct input should be for a 2D file with same Bs in both directions for this case.
But I cannot use the new version in the same manner as the old one.

**Comment by tommy-engels** [comment]
fixed in latest commit

**Comment by tommy-engels** [comment]
it turns out it was not fixed at all!
but I hope now it is.
