### ISSUE TITLE
CDF42 unit test fail - link with reset_ghost_nodes

### ISSUE THREAD

**Issue by tommy-engels** [adaptive-cfd/WABBIT#60]
On my machine and using the latest version, one of the unit tests does fail in a suspicous manner:

```
Running test:  TESTING/conv/blob_2D_adaptive_CDF42/blob-convection-adaptive.sh
Writing output to:  TESTING/conv/blob_2D_adaptive_CDF42/blob-convection-adaptive.log
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 3 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode 280420232.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
 fail  	Time used in test: 2 seconds
```

when looking at the logfile, it reads

```
IO: Saving data triggered, time= 0.15000000    
IO: saving HDF5 file t=     0.15000000 file = phi_000000150000.h5 J=( 1 |  2) Nblocks=      7 sparsity=( 43.8% /   0.0%)
RUN: it=     19 time=     0.150000000 t_wall=9.234E-03 Nb=(    40/     7) J=( 2: 3/ 1: 2) dt= 6.3E-03 mem=  0% adapt iter Nb:(    16)
   932341.99218895088     
large values in phi. that cannot be good.
```

upon further inspection, I realized that the test is indeed running fine (the data look okay, even if stored for every time step), and that the failure may have to do with the `reset_ghost_nodes` routine that you have activated if `DEV` is using at compile-time.

Are you aware of this issue ?

**Comment by Arcadia197** [comment]
I am aware of this issue. I thought it was diverging due to the time-stepping.
What I mentioned in on of the commits was:

> test blob_2D_CDF42 strangely diverged, when changing CFL to a smaller value (0.8) it works fine - I don't know what is going on there

But you are right it works when unsetting the DEV flag, so there is something.

**Comment by tommy-engels** [comment]
Yes, indeed it does work with `unset DEV`.
