### ISSUE TITLE
integration does count redundant nodes twice?

### ISSUE THREAD

**Issue by tommy-engels** [adaptive-cfd/WABBIT#7]
the integration of, e.g. mean flow, for instance

params_acm%mean_flow(1) = params_acm%mean_flow(1) + sum(u(g+1:Bs+g, g+1:Bs+g, 1, 1))*dx(1)*dx(2)

appears to be counting the redundant nodes twice; shouldn't the array boundary be

params_acm%mean_flow(1) = params_acm%mean_flow(1) + sum(u(g+1:Bs+g-1, g+1:Bs+g-1, 1, 1))*dx(1)*dx(2)

instead??

**Comment by SophieMutzel** [comment]
I remember having changed that once in the master branch (see https://github.com/adaptive-cfd/WABBIT/commit/0a55c5d0e28f70a79ebe5f53527b1ba83521b22c) which I pushed apparently exactly one day after you created the new physics branch and then did not change it there.
