### ISSUE TITLE
Ghost node sync on domain boarders does creepy things

### ISSUE THREAD

**Issue by Philipp137** [adaptive-cfd/WABBIT#9]
I have created a video of my sod shock tube. It seems that with the new jmax the sync of the domain boundaries fails.
The initial condition is already wrong. Here I initialize my field with a simple if statement:
if (x < Lx/2)
     p=1
else
   p=0.1
end
but in the plot there are wrong values on the boundaries, which seem to be not synced right. This error increases for further time iterations until my program fails. Note that this is without any filtering.
 
Please check out the gif I exported to visualize my problem:
![output](https://user-images.githubusercontent.com/12294204/40115030-9b7f5148-58fe-11e8-83a7-11c87950b2c8.gif)

**Comment by SophieMutzel** [comment]
I get an error in the redundant ghost nodes check when reading a field from a file. Maybe this has something to do with it?

 Testing redundant nodes on initial condition..
ERROR: difference in redundant nodes   9.9900E+99 level_diff=-1 hvy_id=       6 rank=    0
ERROR: difference in redundant nodes   9.9900E+99 level_diff=-1 hvy_id=      86 rank=    1
ERROR: difference in redundant nodes   9.9900E+99 level_diff=-1 hvy_id=      15 rank=    2

**Comment by tommy-engels** [comment]
This issue is closed: it is important to be sure that redundant points are truely redundant, not to 1e-16. This was the case in Philipps sine-wave perturbation: ux=sin(0) is not the same as ux=sin(2*pi)
